server:
  port: 8080
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    #create database scanlator character set utf8mb4 collate utf8mb4_0900_ai_ci
    url: jdbc:mysql://scanlator-db/scanlator?zeroDateTimeBehavior=CONVERT_TO_NULL
    username: root
    password: scanlator
  devtools:
    remote:
      secret: scanlator
# jpa
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
       ddl-auto: none
       naming:
        physical-strategy:
          org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true