CREATE TABLE PROFILE(
	ID BIGINT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(200) NOT NULL
);

CREATE TABLE USER_PROFILE(
	USER_ID BIGINT(20) NOT NULL,
    PROFILE_ID BIGINT(20) NOT NULL,
    FOREIGN KEY (USER_ID) references USER(ID),
    FOREIGN KEY (PROFILE_ID) references PROFILE(ID),
	PRIMARY KEY(USER_ID, PROFILE_ID)
);
